# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-09 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Infos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipcode', models.PositiveSmallIntegerField()),
                ('middlename', models.CharField(max_length=20)),
                ('full_name', models.CharField(max_length=50)),
                ('age', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'UsedInfo',
                'verbose_name_plural': 'UsedInfos',
            },
        ),
    ]
