# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-11 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infos',
            name='age',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='infos',
            name='full_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='infos',
            name='middlename',
            field=models.CharField(default='', max_length=20),
        ),
    ]
