# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-11 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_monitor', '0002_auto_20170611_2106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infos',
            old_name='full_name',
            new_name='l_name',
        ),
        migrations.AddField(
            model_name='infos',
            name='f_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
