# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_monitor', '0003_auto_20170611_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='infos',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='infos',
            name='links',
            field=models.URLField(default=''),
        ),
    ]
