# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_monitor', '0005_auto_20170612_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infos',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='infos',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='infos',
            name='links',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='infos',
            name='middlename',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
