# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_monitor', '0006_auto_20170612_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infos',
            name='links',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
