# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_monitor', '0007_auto_20170613_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infos',
            name='links',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
