# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-16 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_monitor', '0008_auto_20170613_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infos',
            name='links',
            field=models.TextField(blank=True),
        ),
    ]
