# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-24 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_monitor', '0009_auto_20170616_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='infos',
            name='myfile',
            field=models.FileField(null=True, upload_to='media'),
        ),
    ]
