# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-24 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_monitor', '0010_infos_myfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infos',
            name='myfile',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
