# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-25 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_monitor', '0011_auto_20170624_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='infos',
            name='where',
            field=models.CharField(choices=[('A', 'RET'), ('B', 'CARDENZE')], max_length=50, null=True),
        ),
    ]
