# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-25 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_monitor', '0013_auto_20170624_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='infos',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
