# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-27 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_monitor', '0014_infos_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='infos',
            name='status',
            field=models.CharField(choices=[('found', 'yes'), ('not_found', 'no')], max_length=20, null=True),
        ),
    ]
